# https://docs.github.com/en/actions/writing-workflows/quickstart

on:
  release:
    types: [created]
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - master

jobs:
  unit_tests:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Install depends
        run: |
          sudo apt-get update
          sudo apt-get install nasm gcc make
      - name: Build source code
        run: |
          make
      - name: Run unit test
        run: |
          ./bin/runtest
      - name: List build outputs
        run: find . -type f -not -path './.git/*' | sort
